-- ============================================================
-- Khien Ha -- Clean Seed Database
-- Generated: 2026-05-05
-- Includes: schema (all tables) + default site_contents
-- Does NOT include: news, contact_messages, sessions, cache
-- To restore: mysql -u root -p khienha < khienha-seed.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS `khienha`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `khienha`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------
-- users
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id`                bigint unsigned NOT NULL AUTO_INCREMENT,
  `name`              varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email`             varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password`          varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token`    varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at`        timestamp NULL DEFAULT NULL,
  `updated_at`        timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Admin user (password: KhienHa@123456)
-- Hash generated by: php artisan tinker --execute="echo bcrypt('KhienHa@123456');"
-- Replace the hash below with the output from your server if needed.
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`) VALUES
(1,'Khien Ha Admin','admin@khienha.vn',NULL,'$2y$12$USRj/0qnmFsB6KjYa9XfOeVRmjvYGLZv4GtVxvHOD.SNFJ9T.gBM.',NULL,'2026-04-16 00:00:00','2026-04-16 00:00:00');

-- ------------------------------------------------------------
-- password_reset_tokens
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE `password_reset_tokens` (
  `email`      varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token`      varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- sessions
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id`            varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id`       bigint unsigned DEFAULT NULL,
  `ip_address`    varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent`    text COLLATE utf8mb4_unicode_ci,
  `payload`       longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- cache / cache_locks
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `cache`;
CREATE TABLE `cache` (
  `key`        varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value`      mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE `cache_locks` (
  `key`        varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner`      varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_locks_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- jobs / job_batches / failed_jobs
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id`           bigint unsigned NOT NULL AUTO_INCREMENT,
  `queue`        varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload`      longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts`     tinyint unsigned NOT NULL,
  `reserved_at`  int unsigned DEFAULT NULL,
  `available_at` int unsigned NOT NULL,
  `created_at`   int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `job_batches`;
CREATE TABLE `job_batches` (
  `id`              varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name`            varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_jobs`      int NOT NULL,
  `pending_jobs`    int NOT NULL,
  `failed_jobs`     int NOT NULL,
  `failed_job_ids`  longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `options`         mediumtext COLLATE utf8mb4_unicode_ci,
  `cancelled_at`    int DEFAULT NULL,
  `created_at`      int NOT NULL,
  `finished_at`     int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs` (
  `id`         bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid`       varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue`      text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload`    longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception`  longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- site_contents
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `site_contents`;
CREATE TABLE `site_contents` (
  `id`         bigint unsigned NOT NULL AUTO_INCREMENT,
  `key`        varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload`    json NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `site_contents_key_unique` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `site_contents` (`id`,`key`,`payload`,`created_at`,`updated_at`) VALUES
(1,'homepage','{"company":{"name":"CÔNG TY TNHH TM KHIÊN HÀ","shortName":"KHIÊN HÀ","tagline":"Đối tác đóng mới và sửa chữa tàu chuyên nghiệp tại Hải Phòng","description":"Khiên Hà được thành lập từ năm 2002, chuyên đóng mới và sửa chữa tàu nội địa, tàu biển, sà lan biển và các phương tiện thủy chuyên dụng với năng lực đến 25.000 DWT.","establishedYear":"2002"},"hero":{"eyebrow":"Shipbuilding Since 2002","titleLine1":"Năng Lực Đóng Tàu","titleLine2":"Vươn Ra Biển Lớn","subtitle":"Kết hợp đội ngũ kỹ thuật dày dạn kinh nghiệm, hạ tầng hơn 5ha và quy trình quản lý chất lượng nghiêm ngặt để tạo nên những công trình hàng hải bền bỉ, an toàn và đúng tiến độ.","primaryCtaLabel":"Khám phá năng lực","primaryCtaHref":"#services","secondaryCtaLabel":"Xem dự án tiêu biểu","secondaryCtaHref":"#gallery","highlights":[{"label":"25.000 DWT","value":"Năng lực đóng mới"},{"label":"10 tàu","value":"Sửa chữa đồng thời"},{"label":"20+ năm","value":"Kinh nghiệm thực chiến"}]},"about":{"eyebrow":"Về chúng tôi","title":"Nhà máy đóng tàu tư nhân hàng đầu khu vực phía Bắc","highlight":"Hạ tầng lớn, kỹ thuật mạnh, kiểm soát chất lượng chặt.","description":"Khiên Hà đầu tư đồng bộ từ công nghệ cắt CNC, thiết bị nâng hạ trọng tải lớn, hệ thống bắn cát phun sơn đến đội ngũ kỹ sư, thợ lành nghề nhằm bảo đảm hiệu quả thi công cho từng dự án đóng mới và sửa chữa tàu.","image":"https://khienha.vn/uploads/anh/367316468994953.jpg","certificateLabel":"ISO 9001:2015","certificateText":"Hệ thống quản lý chất lượng cho hoạt động đóng mới và sửa chữa tàu thủy.","videoUrl":""},"contact":{"eyebrow":"Liên hệ","title":"Kết nối với Khiên Hà","description":"Gửi nhu cầu đóng mới, sửa chữa, đại tu hoặc tư vấn kỹ thuật để đội ngũ chúng tôi phản hồi nhanh chóng.","address":"Xã Chiến Thắng, huyện An Lão, Hải Phòng, Việt Nam","phone":"(+84-31) 3903088","fax":"(+84-31) 3903088","hotline":"0913 598 034","email":"khienhadongtau18@gmail.com"},"history":[{"id":1,"year":"2002","title":"Thành lập","content":"Công ty TNHH TM Khiên Hà chính thức hoạt động tại Hải Phòng, định hướng chuyên sâu lĩnh vực đóng mới và sửa chữa phương tiện thủy."},{"id":2,"year":"2007","title":"Mở rộng cơ sở","content":"Doanh nghiệp mở rộng mặt bằng và dây chuyền sản xuất để đáp ứng nhu cầu đóng sửa tàu ngày càng lớn của thị trường."},{"id":3,"year":"2010","title":"Chuyển về An Lão","content":"Nhà máy chuyển về xã Chiến Thắng, An Lão với quy mô hạ tầng lớn hơn, tối ưu cho đóng tàu trọng tải cao."},{"id":4,"year":"2016","title":"Chuẩn hóa quy trình","content":"Bổ sung quy trình kiểm soát kỹ thuật, hồ sơ nghiệm thu và giám sát chất lượng theo từng hạng mục sản xuất."},{"id":5,"year":"2021","title":"Nâng cấp năng lực","content":"Được đánh giá và cấp chứng nhận năng lực đóng mới tàu đến 25.000 DWT, tạo bước tiến lớn về quy mô sản xuất."},{"id":6,"year":"2025","title":"Mở rộng phân khúc dự án","content":"Tiếp nhận đồng thời nhiều gói đóng mới, cải hoán và sửa chữa tàu hàng, sà lan biển và tàu dịch vụ kỹ thuật."}],"capacity":[{"id":1,"category":"Nhân sự","title":"Đội ngũ kỹ thuật và công nhân lành nghề","detail":"Lực lượng kỹ sư, tổ trưởng và công nhân nhiều năm kinh nghiệm, quen thuộc với các hạng mục đóng mới, cải hoán và sửa chữa phương tiện thủy từ nội địa đến quốc tế.","icon":"Users","image":"https://khienha.vn/uploads/anh/233516468994642.jpg"},{"id":2,"category":"Hạ tầng","title":"Nhà xưởng và triền tàu quy mô lớn","detail":"Diện tích hơn 5ha, nhà xưởng trên 4.500m2, hệ thống đường triền cứng dài khoảng 300m, đủ điều kiện phục vụ đóng mới tàu có tải trọng lớn.","icon":"Building2","image":"https://khienha.vn/uploads/anh/367316468994953.jpg"},{"id":3,"category":"Thiết bị","title":"Cẩu, máy cắt và gia công chính xác","detail":"Trang bị dầm cổng trục 200 tấn, 100 tấn, dàn cẩu trục 60 tấn, 30 tấn cùng hệ thống CNC phục vụ sản xuất kết cấu chính xác và an toàn.","icon":"Cpu","image":"https://khienha.vn/uploads/anh/299816468995344.jpg"},{"id":4,"category":"Công nghệ bề mặt","title":"Bắn cát, phun sơn và hoàn thiện đồng bộ","detail":"Hệ thống khí nén khép kín, năng suất cao giúp xử lý bề mặt, sơn phủ và hoàn thiện đạt chuẩn kỹ thuật cho nhiều loại tàu và sà lan biển.","icon":"Wind","image":"https://khienha.vn/uploads/anh/639616469009097.jpg"},{"id":5,"category":"Điều hành dự án","title":"Tổ chức thi công theo tiến độ nhiều mũi","detail":"Phân luồng công việc theo từng block thân tàu, thiết bị máy, hệ trục và hệ điện để rút ngắn thời gian thi công các dự án trọng điểm.","icon":"Users","image":"https://khienha.vn/uploads/anh/724016468995605.jpg"},{"id":6,"category":"Bến bãi","title":"Bãi lắp ráp và khu tập kết vật tư rộng","detail":"Khu tập kết tôn thép, thiết bị và block thành phẩm được bố trí liền mạch với tuyến vận chuyển nội bộ, giảm thời gian chờ và tăng năng suất.","icon":"Building2","image":"https://khienha.vn/uploads/anh/810916469000106.jpg"}],"quality":{"title":"Quy trình quản lý chất lượng nhiều lớp","description":"Khiên Hà kiểm soát chất lượng từ khâu tiếp nhận vật tư, gia công, lắp ráp, thử nghiệm đến bàn giao nhằm bảo đảm độ an toàn, độ bền và tiến độ dự án.","image":"https://khienha.vn/uploads/tintuc/1701647416008iso.png","mainImage":"https://khienha.vn/uploads/tintuc/1701647416008iso.png","steps":[{"id":1,"step":"Bước 1","title":"Kiểm tra vật tư đầu vào, chứng chỉ thép và hồ sơ kỹ thuật trước khi gia công."},{"id":2,"step":"Bước 2","title":"Giám sát công đoạn cắt, tạo hình, lắp ráp và hàn thân tàu theo bản vẽ được phê duyệt."},{"id":3,"step":"Bước 3","title":"Đo kiểm sai số kích thước, kiểm tra mối hàn và hiệu chỉnh trước khi chuyển sang công đoạn tiếp theo."},{"id":4,"step":"Bước 4","title":"Kiểm tra hệ trục, máy chính, điện tàu, sơn phủ và hoàn thiện kỹ thuật theo checklist bàn giao."},{"id":5,"step":"Bước 5","title":"Nghiệm thu nội bộ, chạy thử và hoàn thiện hồ sơ bàn giao theo tiêu chuẩn hiện hành."}]},"goals":[{"id":1,"title":"Tầm nhìn 2030","content":"Trở thành đối tác đóng mới và sửa chữa tàu uy tín hàng đầu khu vực miền Bắc, đủ năng lực đáp ứng các dự án ngày càng phức tạp."},{"id":2,"title":"Sứ mệnh","content":"Mang đến những công trình hàng hải an toàn, bền bỉ và hiệu quả kinh tế cho khách hàng trong và ngoài nước."},{"id":3,"title":"Cam kết chất lượng","content":"Tập trung vào chất lượng, tiến độ, an toàn lao động và dịch vụ hậu mãi minh bạch trong toàn bộ vòng đời dự án."},{"id":4,"title":"Nâng cấp nhân lực","content":"Đầu tư đào tạo đội ngũ kỹ sư, cán bộ hiện trường và công nhân nòng cốt để đáp ứng yêu cầu kỹ thuật cao hơn mỗi năm."},{"id":5,"title":"Phát triển khách hàng dài hạn","content":"Xây dựng quan hệ đối tác bền vững với chủ tàu, đơn vị logistics và doanh nghiệp vận tải thủy trên toàn quốc."}],"gallery":[{"id":1,"url":"https://khienha.vn/uploads/anh/79371608532527Tau 9000T.jpg","title":"Tàu hàng 9.000T","category":"Đóng mới"},{"id":2,"url":"https://khienha.vn/uploads/anh/89831647418380Tau du lich.jpg","title":"Tàu du lịch cao cấp","category":"Dự án du lịch"},{"id":3,"url":"https://khienha.vn/uploads/anh/92011647418432Tau ca nghe luoi chup.jpg","title":"Tàu cá vỏ thép","category":"Nghề cá"},{"id":4,"url":"https://khienha.vn/uploads/anh/233516468994642.jpg","title":"Lắp ráp phân đoạn","category":"Thi công"},{"id":5,"url":"https://khienha.vn/uploads/anh/299816468995344.jpg","title":"Xưởng cơ khí","category":"Nhà xưởng"},{"id":6,"url":"https://khienha.vn/uploads/anh/639616469009097.jpg","title":"Sà lan biển tải trọng lớn","category":"Sản phẩm"},{"id":7,"url":"https://khienha.vn/uploads/anh/367316468994953.jpg","title":"Khu triền tàu ngoài bãi","category":"Hạ tầng"},{"id":8,"url":"https://khienha.vn/uploads/anh/724016468995605.jpg","title":"Lắp đặt block thân tàu","category":"Thi công"},{"id":9,"url":"https://khienha.vn/uploads/anh/810916469000106.jpg","title":"Tập kết vật tư dự án","category":"Vận hành"},{"id":10,"url":"https://khienha.vn/uploads/anh/7851646900891Tau%20du%20lich.jpg","title":"Hoàn thiện tàu du lịch","category":"Bàn giao"}],"banners":["https://khienha.vn/uploads/anh/367316468994953.jpg","https://khienha.vn/uploads/anh/299816468995344.jpg","https://khienha.vn/uploads/anh/724016468995605.jpg","https://khienha.vn/uploads/anh/810916469000106.jpg","https://khienha.vn/uploads/anh/7851646900891Tau%20du%20lich.jpg","https://khienha.vn/uploads/anh/639616469009097.jpg","https://khienha.vn/uploads/anh/233516468994642.jpg","https://khienha.vn/uploads/anh/79371608532527Tau 9000T.jpg"]}','2026-04-16 00:00:00','2026-04-16 00:00:00');

-- ------------------------------------------------------------
-- news
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `news`;
CREATE TABLE `news` (
  `id`           bigint unsigned NOT NULL AUTO_INCREMENT,
  `title`        varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug`         varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category`     varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt`      text COLLATE utf8mb4_unicode_ci,
  `content`      longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_path`   longtext COLLATE utf8mb4_unicode_ci,
  `published_at` timestamp NULL DEFAULT NULL,
  `is_featured`  tinyint(1) NOT NULL DEFAULT '0',
  `is_published` tinyint(1) NOT NULL DEFAULT '1',
  `created_at`   timestamp NULL DEFAULT NULL,
  `updated_at`   timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `news_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- (news rows omitted -- restore from khienha-current.sql or re-seed via NewsSeeder)

-- ------------------------------------------------------------
-- contact_messages
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `contact_messages`;
CREATE TABLE `contact_messages` (
  `id`         bigint unsigned NOT NULL AUTO_INCREMENT,
  `name`       varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone`      varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email`      varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company`    varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message`    longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `status`     varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'new',
  `notes`      text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- migrations (Laravel internal)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id`        int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch`     int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`id`,`migration`,`batch`) VALUES
(1,'0001_01_01_000000_create_users_table',1),
(2,'0001_01_01_000001_create_cache_table',1),
(3,'0001_01_01_000002_create_jobs_table',1),
(4,'2026_04_16_000100_create_site_contents_table',1),
(5,'2026_04_16_000200_create_news_table',1),
(6,'2026_04_16_000300_create_contact_messages_table',1),
(7,'2026_04_16_000400_change_news_image_path_to_longtext',1);

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- NOTES
-- • Trường about.videoUrl đã được thêm vào payload (giá trị mặc định "")
-- • Để set URL YouTube thật: vào Admin > Nội dung trang > Link YouTube
-- • Để lấy full backup (kèm tin tức + ảnh): chạy trên server:
--     php scripts/export-current-db.php
-- • Để re-seed tin tức mẫu:
--     php artisan db:seed --class=NewsSeeder
-- • Admin mặc định: admin@khienha.vn / KhienHa@123456
--   (hash trong file này có thể cần regenerate trên server mới)
-- ============================================================
